version: '3.8'

networks:
  drf:
    external: true

services:
  db:
    image: postgres:latest
    container_name: drf_db
    restart: always
    environment:
      - POSTGRES_DB=drf_db
      - POSTGRES_USER=drf_admin
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

    networks:
      - drf

volumes:
  db: